### ISSUE TITLE
TIA and Dreamer Question

### ISSUE THREAD

**Issue by gunnxx** [facebookresearch/denoised_mdp#17]
Hi, thanks for the great paper and great code!

I am wondering
1. Can I reproduce TIA results using this codebase?
2. You said the RSSM is modified from the unofficial pytorch implementation with some inconsistencies fixed. May I know what kind of inconsistencies since I am using the unofficial pytorch implementation as well.

Thank you

**Comment by ssnl** [comment]
> Can I reproduce TIA results using this codebase?

No, sorry. You can use the TIA official release though.

> You said the RSSM is modified from the unofficial pytorch implementation with some inconsistencies fixed. May I know what kind of inconsistencies since I am using the unofficial pytorch implementation as well.

I am sorry that I don't recall the exact details... You can try to compare the code in this repo and the one we based on, to spot differences.
