### ISSUE TITLE
attrs not set by command in README

### ISSUE THREAD

**Issue by CuriousG102** [facebookresearch/denoised_mdp#9]
Followed instructions in https://github.com/facebookresearch/denoised_mdp/issues/7 to no avail.

**Comment by CuriousG102** [comment]
Refinement to this issue report: The problem is actually that [this line](https://github.com/facebookresearch/denoised_mdp/blob/e5d5d7318977cfa56355d1c366c1106207c409c9/config.py#L78) runs before overrides can take effect.

**Comment by ssnl** [comment]
Hi Mike, could you post the command you run, the output you got, and what made you think that the `exist_path` definition is problematic?

**Comment by CuriousG102** [comment]
Sure. Run any example command with `output_base_dir=<some other directory>`, after having deleted the `results` folder. Please let me know if you need an exact command to use instead of adding the existing flag to one of the commands in your README. I'm working on a fork of the repo so the exact command I ran will have problems at HEAD.

**Comment by CuriousG102** [comment]
No. The directory exists. The problem is that the validator will look for `results` regardless of whether that's what you set `output_base_dir` to in the CLI, because it's running before the CLI value is set on the config.

**Comment by ssnl** [comment]
Sorry, deleting `results` is not supported. You can set base directory to a different one, or even redirect `results`.
